server:
    port: '8762'
spring:
    application:
        name: zuul-service
eureka:
    instance:
        preferIpAddress: 'true'
    client:
        registerWithEureka: 'true'
        fetchRegistry: 'true'
    serviceurl:
        defaultzone: 'http://localhost:8761/eureka/'
management:
    security:
        enabled: 'false'
zuul:
    routes:
        content:
            url: 'http://localhost:65485/content'
logging:
    file: zuul.log
    level: FINEST