server:
    port: '8762'
spring:
    application:
        name: zuul-service
eureka:
    instance:
        hostname: localhost
        preferIpAddress: 'false'
    client:
        enabled: 'true'
        registerWithEureka: 'true'
        fetchRegistry: 'true'
    serviceurl:
        defaultzone: 'http://localhost:8761/eureka/'
management:
    security:
        enabled: 'false'
zuul:
    routes:
        content:
            path: /content/**
            serviceId: content
            #url: 'http://localhost:65485/content'
            stripPrefix: false
        checkout:
            path: /checkout/**
            serviceId: checkout
            #url: 'http://localhost:65485/checkout'
            stripPrefix: false
        inventory:
            path: /inventory/**
            serviceId: inventory
            #url: 'http://localhost:65485/inventory'
            stripPrefix: false
        payment:
            path: /payment/**
            serviceId: payment
            #url: 'http://localhost:65485/payment'
            stripPrefix: false
logging:
    file: zuul.log
    level: FINEST
ribbon:
    eureka:
        enabled: true
    ConnectTimeout: 30000
    ReadTimeout: 60000
hystrix: 
 command: 
   default: 
     execution: 
       isolation: 
         thread: 
           timeoutInMilliseconds: 40000000